### ISSUE TITLE
labels dont work correctly

### ISSUE THREAD

**Issue by utahisnotastate** [dgonz64/rhfa-material-ui#2]
Hi!

I like your library but im not sure how stuff like labels and placeholders work for inputs. Do you have some super basic example? 

Also is there any support for form sections/groups with different fields in it? 

Also I think labels don't work correctly. Here is a link to a codesandbox using your basic example. The labels dont show up correctly. 

Any help would be greatly appreciated

https://codesandbox.io/s/autumn-moon-in4fp?file=/src/App.js

**Comment by dgonz64** [comment]
Hello!

Thank you very much for your interest in the library and your nice words!

#### Labels

About the labels, that happens because they are not translated. This is intended. The parent library, `react-hook-form-auto`, used translation from the beginning, embedded in the backbone.

[Here](https://codesandbox.io/s/quizzical-euclid-uongj) are the changes to your sandbox in order to show labels correctly. You just import `addTranslations` and fill in the object. [Documentation here](https://github.com/dgonz64/react-hook-form-auto#translation).

I would like to know if it's still a problem for you because I could think of ways to let users opt out of the translation system.

#### Select

The small select input is a bug and I will take a look at it within the day.

#### Groups

Do you mean putting something like a [`<Box />`](https://material-ui.com/components/box/) around arbitrary groups of inputs?

If it's the case, I never though of that, but I think it's a nice idea and will study it carefully in the next days.

**Comment by dgonz64** [comment]
I think I solved everything.

For the select I was able to control width by using an external `<Grid />`. [Take a look here](https://codesandbox.io/s/quizzical-euclid-uongj?file=/src/App.js) for the solution. I added the Material-UI styles by using `makeStyles`.

If you don't want to use a grid, the version `1.1.0` has a bigger default select but I wasn't able to position it pixel-perfect while grid does. If you use that version you should import material-ui too ([documentation updated](https://github.com/dgonz64/rhfa-material-ui/blob/master/README.md)).

For the grouping, if this is what you want, you can [use a sub-model](https://github.com/dgonz64/react-hook-form-auto#types). I made [a new sandbox illustrating the approach](https://codesandbox.io/s/optimistic-mclean-y057g?file=/src/App.js).

**Comment by utahisnotastate** [comment]
You are so awesome! This is amazing. 

Labels/Translation

I am new to using JSON schema for forms, and was having a hard time understanding the translation system. I normally build forms from scratch the old fashioned way, but for my current project that's just not feasible so i've been trying this. I was having a hard time figuring out where physically you had to put the addTranslation and didn't understand what exactly translating was and how I could customie it for my purposes. Thank you so much for clearing that up for me

The external grid is a perfect solution for me, thank you so much for looking into it. I'm seriously ecstatic. I love material UI and all that but i'm still new at it and customizing some small stuff can be pretty difficult sometimes. 

Thank you so much for your help, I've learned more after 2 posts of yours then after like a week or two of banging my head against the wall trying to get these things to work.

**Comment by dgonz64** [comment]
Wow! Thank you! You made me very happy.

If you need something else don't hesitate to ask!

**Comment by dgonz64** [comment]
Updated readme to make this stuff clearer so I'm closing this. Thanks again!
